# ServerProperties
server:
  port: 8080
  servlet:
    context-path: /community

# ThymeleafProperties
spring:
  thymeleaf:
    cache: false
    # DataSourceProperties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///community?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: tangsiyu
    type: com.alibaba.druid.pool.DruidDataSource
  # mailproperties
  mail:
    host: smtp.sina.com
    port: 465
    username: tangsiyu99@sina.com
    password: 2a2dee4385fbdc70
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true #??SSL



# MybatisProperties
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

# logger
#logging:
#  level:
#    com.nowcoder.community: debug
#  file:
#    name: D:/java_workplace/community/community.log


